# Promise对象
> Promise 是异步编程的一种解决方案，比传统的解决方案 "回调函数和事件" 更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。

Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

Promise对象有以下两个特点。
- 对象状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。
- 一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

Promise的缺点:
- 无法取消Promise，一旦新建它就会立即执行，无法中途取消。
- 如果不设置回调函数，Promise内部抛出的错误，不会反应到外部
- 当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

```js
// 异步操作太多，会造成回调地狱，不好理解、调试
funcA(function(info) {
  // 异步操作A成功后执行
  if (info) {
    funcB(function(result) {
      // 异步操作B成功后执行
      if (result) {
        funcC(function(res) {
          // 异步操作B完成后执行
          if (res) {
            // some handler
          } else {
            console.log('异步操作C执行错误')
          }
        })
      } else {
        console.log('异步操作B执行错误')
      }
    })
  } else {
    console.log('异步操作A执行错误')
  }
})

// Promise解决方法
```

## 1.基本用法
Promise对象是一个构造函数，用来生成Promise实例。
```js
// Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。
const promise = new Promise(function(resolve, reject) {
  // ... some code
  if (/* 异步操作成功 */){
    resolve(value); // resolve() 将Promise对象的状态从“未完成”变为“成功”
  } else {
    reject(error); // reject() 将Promise对象的状态从“未完成”变为“失败”
  }
});

// Promise实例生成以后，可以用then方法分别指定resolved状态和rejected状态的回调函数。
// promise.then(函数1，可选的函数2) 这两个函数都接受Promise对象传出的值作为参数。
// 函数1：Promise对象的状态变为resolved时调用
// 函数2：可选，Promise对象的状态变为rejected时调用。
promise.then(function(value) {
  // success
}. function(err) {
  // failure
})
```
### Promise新建后，会立即执行
```js
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');
});

console.log('Hi!');

// Promise
// Hi!
// resolved
```
### Promise封装Ajax操作示例
```js
const getJSON = function(url) {
  const promise = new Promise(function(resolve, reject){
    const handler = function() {
      if (this.readyState !== 4) {
        return;
      }
      if (this.status === 200) {
        resolve(this.response);
      } else {
        reject(new Error(this.statusText));
      }
    };
    const client = new XMLHttpRequest();
    client.open("GET", url);
    client.onreadystatechange = handler;
    client.responseType = "json";
    client.setRequestHeader("Accept", "application/json");
    client.send();

  });

  return promise;
};

getJSON("/posts.json").then(function(json) {
  console.log('Contents: ' + json);
}, function(error) {
  console.error('出错了', error);
});
```
### Promise嵌套另一个Promise
一个Promise里面包含另一个Promise实例做参数
```js
const p1 = new Promise((resolve, reject) => {
    // setTimeout(() => {reject(new Error('fail'))}, 5000)
    setTimeout(() => {resolve(new Error('fail'))}, 5000)
})
const p2 = new Promise((resolve, reject) => {
    setTimeout(()=> {resolve(p1)}, 1000) 
})
p2.then((result) => {
    console.log('resolve')
    console.log(result)
},(err)=> {
    console.log('reject')
    console.log(err)
})
// 如果p1状态为resolve，P2的状态则为resolve
// 如果p1状态为reject，p2的状态则为reject
// 上面代码中，p1是一个 Promise，5 秒之后变为rejected。p2的状态在 1 秒之后改变，resolve方法返回的是p1。由于p2返回的是另一个 Promise，导致p2自己的状态无效了，由p1的状态决定p2的状态。所以，后面的then语句都变成针对后者（p1）。又过了 4 秒，p1变为rejected，导致触发catch方法指定的回调函数。
```
### resolve或reject函数终结
调用resolve或reject并不会终结 Promise 的参数函数的执行。
```js
new Promise((resolve, reject) => {
  resolve(1);  // 如果换成 return resolve(1) 后面的就不会打印了。
  console.log(2);
}).then(r => {
  console.log(r);
});
// 2
// 1
```

## 2.Promise.prototype.then()
```js
// promise.then(函数1，可选的函数2) 这两个函数都接受Promise对象传出的值作为参数。
// 函数1：Promise对象的状态变为resolved时调用
// 函数2：可选，Promise对象的状态变为rejected时调用。
// 返回值：是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。

// 链式写法1：
let getJson = new Promise((resolve, reject)=> {
    setTimeout(()=> {
        resolve({
            name: 'Tom',
            age: 10
        })
    }, 2000)
})
getJson.then((result)=> {  // 接收第一个resolve返回的参数
    console.log('第一个then')
    console.log(result)
    return result
}).then((result2)=> { // 返回新的promise对象后，再次监听resolved状态
    console.log('第二个then')
    console.log(result2)
})

// 第一个then
// {name: "Tom", age: 10}
// 第二个then
// {name: "Tom", age: 10} 


// 链式写法2:
let getJson = new Promise((resolve, reject)=> {
    setTimeout(()=> {
        reject('eeeee') // 会直接
    }, 2000)
})
getJson.then((result)=> {
    console.log('第一个resolve')
    console.log(result)
    return result
}, (err) => {  // 第一个then会触发 reject，当第一个监听到reject后，捕获后，状态就是reslove了。
    console.log('第一个reject')
    console.log(err)
    return err // 如果不return值，第二个resolve就不会接收对应的参数
}).then((result2)=> {
    console.log('第二个resolve')
    console.log(result2)
}, (err) => {
    console.log('第二个reject')
    console.log(err)
})
// 第一个reject
// eeeee
// 第二个resolve
// eeeee

// 链式写法3: Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个.then(null,func)或.catch()语句捕获。
// 当第一个then例没有监听reject时，会触发第二个reject
let getJson = new Promise((resolve, reject)=> {
    setTimeout(()=> {
        reject('eeeee') // 会直接
    }, 2000)
})
getJson.then((result)=> {
    console.log('第一个resolve')
    console.log(result)
    return result
}).then((result2)=> {
    console.log('第二个resolve')
    console.log(result2)
}, (err) => {
    console.log('第二个reject')
    console.log(err)
})
// 第二个reject
// eeeee

// 链式写法4: 上面的例子改良
let getJson = new Promise((resolve, reject)=> {
    setTimeout(()=> {
        reject('eeeee') // 会直接
    }, 2000)
})
getJson.then((result)=> {
    // 监听成功
    console.log('第一个resolve')
    console.log(result)
    return result
}).then(null, (err) => {
    // 监听失败
    console.log('第二个reject')
    console.log(err)
})
```

## 3.Promise.prototype.catch()
Promise.prototype.catch方法是.then(null, rejection)或.then(undefined, rejection)的别名，用于指定发生错误时的回调函数。
```js
// 用catch改良上面最后一个列子
let getJson = new Promise((resolve, reject)=> {
    setTimeout(()=> {
        reject('eeeee') // 会直接
    }, 2000)
})
getJson.then((result)=> {
    // 成功
    console.log('第一个resolve')
    console.log(result)
    return result
}).catch((err) => { // .catch方法是.then(null, rejection)或.then(undefined, rejection)的别名
    // 失败
    console.log('第二个reject')
    console.log(err)
})

// 推荐使用catch写法
// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });
// good
promise
  .then(function(data) { //cb
    // success
  })
  .catch(function(err) {
    // error
  });
```
## 4.Promise.prototype.finally()
finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。
```js
promise
.then(result => {···})
.catch(error => {···})
.finally(() => {···});

// finally本质上是then方法的特例。
promise
.finally(() => {
  // 语句
});

// 等同于
promise
.then(
  result => {
    // 语句
    return result;
  },
  error => {
    // 语句
    throw error;
  }
);

// 简单实现
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

## 5.Promise.all()
Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
```js
const p = Promise.all([p1, p2, p3]);
```
数组里面如果不是 Promise 实例，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理
p的状态由p1、p2、p3决定，分成两种情况。
- 只有p1、p2、p3的状态都变成fulfilled,p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
- 只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数
```js
// 示例1：都返回resolve状态
let p1 = new Promise((resolve, reject)=> {
    setTimeout(()=> resolve(1), 1000)
})
let p2 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(2), 2000)
})
let p3 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(3), 3000)
})
let p = Promise.all([p1, p2, p3])
p.then((results)=> {
    console.log('成功', results)
}).catch((err)=> {
    console.log('失败', err)
})
//  3秒后打印 成功 [1, 2, 3]

// 示例2：其中一个reject 2
let p1 = new Promise((resolve, reject)=> {
    setTimeout(()=> resolve(1), 1000)
})
let p2 = new Promise((resolve, reject)=> {
   setTimeout(()=> reject(2), 2000)
})
let p3 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(3), 3000)
})
let p = Promise.all([p1, p2, p3])
p.then((results)=> {
    console.log('成功', results)
}).catch((err)=> {
    console.log('失败', err)
}) 
// 失败 2

// 示例3：其中一个reject被捕获
let p1 = new Promise((resolve, reject)=> {
    setTimeout(()=> reject(1), 1000)
}).then((result)=> {
    console.log(`p1 resovle: ${result}`)
}).catch((err)=> {
    console.log(`p1 reject: ${err}`)
    return 'some info'   // 如果不return，promise.all 接收的值会是undefined
})
let p2 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(2), 2000)
})
let p3 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(3), 3000)
})
let p = Promise.all([p1, p2, p3])
p.then((results)=> {
    console.log(results)
}).catch((err)=> {
    console.log(err)
})
// p1 reject: 1
// ['some info', 2, 3]

// 示例4：捕获resolve或reject后，对返回值的影响
let p1 = new Promise((resolve, reject)=> {
    setTimeout(()=> reject(1), 1000)
}).then((result)=> {
    console.log(`p1 resovle: ${result}`)
}).catch((err)=> {
    console.log(`p1 reject: ${err}`)
    return 'some info'   // 如果不return，promise.all 接收的值会是undefined
})
let p2 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(2), 2000)
}).then((result)=> {
    console.log(`p2 resolve ${result}`)
    // 如果这里接收了resolve的值，没有return，那么Promise.all 接收的值会是undefined
})
let p3 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(3), 3000)
})
let p = Promise.all([p1, p2, p3])
p.then((results)=> {
    console.log(results)
}).catch((err)=> {
    console.log(err)
})
// p1 reject: 1
// p2 resolve 2
//  ["some info", undefined, 3]
```

## 6.Promise.race()
Promise.race方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
```js
const p = Promise.race([p1, p2, p3]);

// 只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。
// 3个resolve的情况
let p1 = new Promise((resolve, reject)=> {
    setTimeout(()=> resolve(1), 1000)
})
let p2 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(2), 2000)
})
let p3 = new Promise((resolve, reject)=> {
   setTimeout(()=> resolve(3), 3000)
})
let p = Promise.race([p1, p2, p3])
p.then((results)=> {
    console.log(results)
}).catch((err)=> {
    console.log(err)
})
// 1   返回最先改变状态的promise实例
```
### 请求超时处理
如果 5 秒之内fetch方法无法返回结果，变量p的状态就会变为rejected，从而触发catch方法指定的回调函数。
```js
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
```
## 7.Promise.resolve()
有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用。
```js
// 1. 如果参数是一个Promise对象，则原封不动返回该对象。
let p1 = new Promise((resolve, reject)=> {
    setTimeout(() => {resolve(1)}, 1000)
})
let p = Promise.resolve(p1)
p1 === p  // true


// 2.如果参数是一个具有then方法的对象
// Promise.resolve方法会将这个对象转为 Promise 对象，然后就立即执行thenable对象的then方法。
let thenable = {
    then: function(resolve, reject) {
        resolve(42)
    }
}
let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value); 
});
// 42


// 3. 如果参数不是具有then方法的对象，或根本就不是对象
会返回一个promise对象，状态为resolve
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))

const p = Promise.resolve('Hello');
p.then(function (s){
  console.log(s)
});
// hello


// 4. 如果参数为空，没参数 Promise.resolve()
// Promise.resolve()方法允许调用时不带参数，直接返回一个resolved状态的 Promise 对象。
Promise.resolve().then((result)=> {
    console.log('get resolve')
})
// get resolve

// 执行顺序问题
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');
// one
// two
// three

// 立即resolve()的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时。
// setTimeout(fn, 0)在下一轮“事件循环”开始时执行，Promise.resolve()在本轮“事件循环”结束时执行，console.log('one')则是立即执行，因此最先输出。
```

## 8.Promise.reject()
Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。
```js
const p = Promise.reject('出错了');
// 等同于
const p = new Promise((resolve, reject) => reject('出错了'))

p.then(null, function (s) {
  console.log(s)
});
// 出错了


// Promise.reject()方法的参数，会原封不动地作为reject的理由
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable).catch(e => {
  console.log(e === thenable)
})
// true
```
## 9.应用
### 加载图片
```js
const preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    const image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
```
### Generator 函数与 Promise 的结合
使用 Generator 函数管理流程，遇到异步操作的时候，通常返回一个Promise对象。

## 10.Promise.try()
Promise.try就是模拟try代码块，就像promise.catch模拟的是catch代码块。
```js
Promise.try(() => database.users.get({id: userId}))
  .then(...)
  .catch(...)
```
